
# name: Deploy to Firebase Hosting

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Install Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install Firebase CLI
#         run: npm install -g firebase-tools

#       - name: Install Dependencies
#         run: npm ci

#       - name: Create .env file with secrets
#         run: |
#           echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

#       - name: Build Project
#         run: npm run build

#       - name: Check if Build Folder Exists
#         run: |
#           if [ ! -d "dist" ]; then
#             echo "Error: Build directory 'dist/' does not exist! Deployment failed."
#             exit 1
#           fi

#       - name: Write Firebase Service Account Key to File
#         run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json

#       - name: Deploy to Firebase
#         run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive
#         env:
#           GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json





name: CI/CD Pipeline with Security Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file with secrets
        run: |
          echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Build project
        run: npm run build

      - name: Check if build folder exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: Build directory 'dist/' does not exist! Deployment failed."
            exit 1
          fi

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write Firebase service account key to file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

  
          # zap-scan:
          #   runs-on: ubuntu-latest
          #   steps:
          #     - name: Run OWASP ZAP Baseline Scan
          #       uses: zaproxy/action-baseline@v0.4.0
          #       with:
          #         target: 'https://studentmate-2b859.web.app'
          #         docker_name: 'zaproxy/zap-stable'
        

  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks to detect secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
