
# name: Deploy to Firebase Hosting

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Install Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install Firebase CLI
#         run: npm install -g firebase-tools

#       - name: Install Dependencies
#         run: npm ci

#       - name: Create .env file with secrets
#         run: |
#           echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

#       - name: Build Project
#         run: npm run build

#       - name: Check if Build Folder Exists
#         run: |
#           if [ ! -d "dist" ]; then
#             echo "Error: Build directory 'dist/' does not exist! Deployment failed."
#             exit 1
#           fi

     
#       - name: Write Firebase Service Account Key to File
#         run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json

#       - name: Deploy to Firebase
#         run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive
#         env:
#           GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json





# 2nd failed attempt

# name: Deploy to Firebase Hosting

# on:
#   push:
#     branches: [main]  

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Install Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install Firebase CLI
#         run: npm install -g firebase-tools

#       - name: Install dependencies
#         run: npm ci

#       - name: Create .env file
#         run: |
#           echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

#       - name: Build project
#         run: npm run build

#       - name: Verify build folder exists
#         run: |
#           if [ ! -d "dist" ]; then
#             echo "Error: dist/ not found!"
#             exit 1
#           fi

#       - name: Write service account
#         run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json

#       - name: Deploy to Firebase
#         run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive
#         env:
#           GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json



#=====


name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm ci  

      - name: Build Project
        run: npm run build

      - name: Check if Build Folder Exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: Build directory 'dist/' does not exist! Deployment failed."
            exit 1
          fi

      - name: Authenticate with Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: firebase use --add ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive
